version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: eventflow-api:local
    container_name: eventflow-api
    ports:
      - "4053:4053"
    environment:
      - GO_ENV=development
    networks:
      - eventflow-net

  postgres:
    image: postgres:17
    container_name: eventflow-postgres
    environment:
      POSTGRES_DB: eventflow
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  eventflow-net:
    driver: bridge
